application: irpagnossin-test
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /static
  static_dir: static
- url: /favicon\.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon\.ico
- url: .*
  script: main.app



libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: "2.6"

  
